### ISSUE TITLE
ToChannelT release?

### ISSUE THREAD

**Issue by buddhamangler-cbre** [ahmetb/go-linq#103]
I'm having an issue getting a release with ToChannelT in it following the install directions for this package.  Is there a planned release coming up with that or is there an alternative way to get get the package such that I get the version with that method?  go get doesn't seem to be able to get by tag or at least it is not working for me.

**Comment by ahmetb** [comment]
I just tagged v3.2.0, let me know if it fixes the situation.

**Comment by buddhamangler-cbre** [comment]
Works, thank you!
