### ISSUE TITLE
update website

### ISSUE THREAD

**Issue by kalaninja** [ahmetb/go-linq#56]
@cleitonmarx what do you think about updating the [site](http://ahmetalpbalkan.github.io/go-linq/). You can add some info/examples of the new -T methods api and add some info about yourself.

**Comment by cleitonmarx** [comment]
@kalaninja Sure, I'll try this weekend!

**Comment by ahmetalpbalkan** [comment]
I think our README/godoc examples got pretty cool lately and this website thing started to become a bit of a hassle. Am I the only one feeling that way or is the website still a good ramp-up/discovery source?

Here are the daily analytics for the website for the past month:

![image](https://cloud.githubusercontent.com/assets/159209/21734407/17576a16-d418-11e6-9566-d70ad4be3222.png)

...and monthly for the past year:

![image](https://cloud.githubusercontent.com/assets/159209/21734423/2ab9a696-d418-11e6-969a-8107f4983e14.png)

We get _some_ traffic back to GitHub from the website, but not a lot:

> 
![image](https://cloud.githubusercontent.com/assets/159209/21734444/40ae02b2-d418-11e6-904a-52c87e265914.png)

**Comment by kalaninja** [comment]
I personally like the website, it much clearer and has better design than the readme. Also it is not hard to maintain it.

**Comment by ahmetalpbalkan** [comment]
Anyone wants to patch this? I'm still in favor of shutting the website down. It's cute but it doesn't get many hits and is hard to maintain.

**Comment by cleitonmarx** [comment]
I agree with you @ahmetalpbalkan, I'm ok with the godoc.

**Comment by kalaninja** [comment]
@ahmetb font aren't working now on http://ahmetb.github.io/go-linq/
probably, it is time to decide if we kill the website or not
