### ISSUE TITLE
[announcement] Changing username for the repo

### ISSUE THREAD

**Issue by ahmetb** [ahmetb/go-linq#65]
I am planning to change my GitHub username to `ahmetb` soon. If you already vendored this repo (which you should) this change is not going to break your builds, it may cause issues when you try to update the vendored package.

Leaving this issue open for a while to discuss issues that come up because of the change.

**Comment by kalaninja** [comment]
How about moving go-linq to an organization account, smth like "go-linq team"? I think it gives a more flexible way of managing users and inviting new developers. Also it might be convenient if we decide to implement some extensions in a separate repo, e.g. plinq.
I think it is a common practice for a project getting mature. What do you think? @cleitonmarx ?

**Comment by cleitonmarx** [comment]
I like @kalaninja's idea, I can see many advantages with the organization approach.

**Comment by ahmetalpbalkan** [comment]
I agree, in the long run it's a good idea, but for now we're pretty narrow scoped plus not _very_ popular. There would be arguments on both sides, there are quite a lot of non-org scoped Go projects managed well by a community as well. Let's keep it as is for now until it becomes too tedious to manage anymore.
