### ISSUE TITLE
Does first return a copy?

### ISSUE THREAD

**Issue by artemgrygor** [ahmetb/go-linq#68]
Hi guys,

I'm trying to use the package and either I don't understand something or `First` returns a copy of the element. Here is a simple example:

    collection := Items{
		Item{
			ID:    1,
			Title: "title 1",
		},
		Item{
			ID:    2,
			Title: "title 2",
		},
	}

	item1 := From(collection).FirstWith(func(m interface{}) bool {
		return m.(Item).ID == 2
	})
	fmt.Printf("%p \n", &item1)
	item2 := From(collection).FirstWith(func(m interface{}) bool {
		return m.(Item).ID == 2
	})
	fmt.Printf("%p \n", &item2)

Output:

`0xc4204445d0
0xc4204445e0`

As you can see the same element gets two different address allocation.
How can I get a pointer to my initial element?

**Comment by ahmetb** [comment]
Have you tried `type Items []*Item`?

**Comment by artemgrygor** [comment]
Thanks @ahmetb this one works:

`collection := Items{
		&Item{
			ID:    1,
			Title: "title 1",
		},
		&Item{
			ID:    2,
			Title: "title 2",
		},
	}

	item1 := From(collection).FirstWith(func(m interface{}) bool {
		return m.(*Item).ID == 2
	})
	fmt.Printf("%p \n", item1)
	item2 := From(collection).FirstWith(func(m interface{}) bool {
		return m.(*Item).ID == 2
	})
	fmt.Printf("%p \n", item2)`
