### ISSUE TITLE
Passing in Array of fields for SortByT

### ISSUE THREAD

**Issue by patrickjonesdotca** [ahmetb/go-linq#73]
When looking at a language such as Ruby, one can pass in an array of fields to do multi-level sorting ( i.e. "sort by last name, first name" ).

Currently it does not seem possible to do this in go-linq

**Comment by ahmetb** [comment]
You mean "sort by last name, then if there's tie, sort by first name"?

**Comment by patrickjonesdotca** [comment]
Yes

**Comment by patrickjonesdotca** [comment]
More clearly, sort by last name, then in first name column order alphabetically

**Comment by patrickjonesdotca** [comment]
a Ruby snippet
{code}
Item = Struct.new(:name, :dir, :sort_dir)

entries = [Item.new('favicon.ico', false, 1), Item.new('bin', true, 0),
           Item.new('web.config', false, 1), Item.new('images', true, 0),
           Item.new('global.asax', false, 1), Item.new('content', true, 0)]

entries.sort_by{|e| [e.sort_dir, e.name]}
{code}

**Comment by ahmetb** [comment]
You can do this with [SortT](https://godoc.org/github.com/ahmetb/go-linq#Query.SortT):.

Example:

```go
type Person struct {
    FirstName string
    LastName string
}

From(people).
    SortT(
        func(p1, p2 Person) bool {
            if p1.LastName == p2.LastName {
                return p1.FirstName<p2.FirstName
            }
            return p1.LastName < p2.LastName
        }
    ).ToSlice(...)
```
