### ISSUE TITLE
Query.Difference

### ISSUE THREAD

**Issue by danielzhangy** [ahmetb/go-linq#74]
Hi there,

First of all thanks this cool library.

I'm thinking about there is any plans to extend this lib with func Query.Difference besides Query.Intersect and Query.Union.

**Comment by pellared** [comment]
@danielzhangy 
I think it is already done. Check Query.Except method
https://github.com/ahmetb/go-linq/blob/master/except.go
https://github.com/ahmetb/go-linq/blob/master/except_test.go
Or do you mean something different?

**Comment by ahmetb** [comment]
Yep this sounds like Except().

We mirror .NET LINQ method names as much as possible and Difference() isn't a thing.
