### ISSUE TITLE
Can you give GroupBy version without Query?

### ISSUE THREAD

**Issue by arshpreetsingh** [ahmetb/go-linq#78]
I Want to implement GroupBY for array of slices, and need to apply groupBy operation on That, Can you provide GroupBy() method for the same?

**Comment by ahmetb** [comment]
In that case, the type becomes the slice. I don't think we need to do anything different here. Try using the project yourself a bit.

**Comment by arshpreetsingh** [comment]
ok, Thanks for the insights, I will look into that.
