### ISSUE TITLE
Error returned in Where method

### ISSUE THREAD

**Issue by ocrumbs** [ahmetb/go-linq#8]
I have seen there are lot of methods (ex: Where. Select etc ) that return error type alongside bool type. In all your examples, you are returning nil error. So when to send error other than nil and what happens if there is an error other than nil ? Thanks

**Comment by NoSugarCoffee** [comment]
The link of  wiki: https://github.com/ahmetalpbalkan/go-linq/wiki/Remarks-%26-notes#error-handling is broken

How can i handle error in forEach ?
It seems only panic
