### ISSUE TITLE
How to group by using multiple fields ?

### ISSUE THREAD

**Issue by pradeepkusingh** [ahmetb/go-linq#84]
I have structs with multiple fields and want to group by multiple fields, how can I do it?

**Comment by ahmetb** [comment]
Create a Struct type for those fields and use that value in GroupBy?

**Comment by pradeepkusingh** [comment]
I have a struct with five fields :

date, error, type and I want to group by using all these fields,  I can do it using a single field. but how to do it with multiple fields , like in SQL group by date, type ,error.

**Comment by ahmetb** [comment]
Return the struct itself for grouping?

**Comment by pradeepkusingh** [comment]
Please provide a simple example.. I am a newbie.  appreciate your help.

**Comment by pradeepkusingh** [comment]
This is great library and learning a lot of good things. Thanks for building this.

**Comment by pradeepkusingh** [comment]
ok, I followed above suggestion and it is working. but one issue though..while mapping the data under select getting this error "invalid operation: cannot call non-function i.(linq.Group).Key (value of type interface{})" 

activityError: i.(linq.Group).Key(string),

**Comment by cleitonmarx** [comment]
Here an example: #69

**Comment by pradeepkusingh** [comment]
Thank you @cleitonmarx  @ahmetb

**Comment by pradeepkusingh** [comment]
Sorry to reopen it, while doing select after group by, I keep getting this error

panic: runtime error: hash of unhashable type main.ActivityError

goroutine 1 [running]:
github.com/ahmetb/go-linq.Query.GroupBy.func1(0x0)
        /Users/psingh200/go/pkg/mod/github.com/ahmetb/go-linq@v3.0.0+incompatible/groupby.go:21 +0x1d0
github.com/ahmetb/go-linq.Query.Select.func1(0x146a680)
        /Users/psingh200/go/pkg/mod/github.com/ahmetb/go-linq@v3.0.0+incompatible/select.go:18 +0x33
github.com/ahmetb/go-linq.Query.ToSlice(0xc000268140, 0x145c2c0, 0xc0002680e0)
        /Users/psingh200/go/pkg/mod/github.com/ahmetb/go-linq@v3.0.0+incompatible/result.go:632 +0x1df
main.main()
        /Users/psingh200/go/src/MCcollector/activityerror/IVRError.go:308 +0x595

**Comment by pradeepkusingh** [comment]
linq.From(activityErrorDataList).GroupBy(
		func(i interface{}) interface{} {
			fmt.Println("i.(ActivityError).TrackingID  ")
			return i.(ActivityError)
		},
		func(i interface{}) interface{} { return i.(ActivityError).ActivationType },
	).Select(func(i interface{}) interface{} {

		//fmt.Println("\n\n\n i.(ActivityError)i.(ActivityError)i.(ActivityError)  ", i.(linq.Group).Group)
		return FinalResult{
			//activityError: ,
			//Count:         len(i.(linq.Group).Group),
		}

	}).ToSlice(&results)

**Comment by ahmetb** [comment]
Please investigate. Attach a debugger. Try to learn more go. We can’t support each user of this library individually. Go is a language where all of the source code is easily visible. Google the error message.

**Comment by pradeepkusingh** [comment]
Thanks..
