### ISSUE TITLE
bug in WhereIndexed

### ISSUE THREAD

**Issue by quexer** [ahmetb/go-linq#86]
I believe `WhereIndexed` doesn't work as design:

https://play.golang.org/p/HD5-rxIkpx0

```
package main

import (
	"fmt"

	"github.com/ahmetb/go-linq/v3"
)

func main() {

	r := linq.Range(1, 10).
		WhereIndexed(func(i int, _ interface{}) bool {
			return i%3 == 0
		}).
		Results()
	fmt.Println(r)
}
```
output of the code above  is
 `[1 2 3 4 5 6 7 8 9 10]`
instead of 
`[3 6 9]`

maybe the bug is here

https://github.com/ahmetb/go-linq/blob/master/where.go#L61

thanks!

**Comment by ahmetb** [comment]
Hmm this looks legitimate. So you're saying this is a variable reused unintentionally?

Do you mind adding a test case for it so we can clearly see this fail. I'm also surprised we don't have such a case unit tested already.

**Comment by quexer** [comment]
hi,  here's the test case:

I think index behavior should be the same no matter what predicate is provided. otherwise, we could not do  `index-based filtering` with  `WhereIndexed`

thanks 

```
package main

import (
	"testing"

	"github.com/ahmetb/go-linq/v3"
)

var l = []string{"a", "b", "c", "d"}

// this will fail
func TestWhereIndexedWithTruePredicate(t *testing.T) {
	var idx int
	linq.From(l).WhereIndexed(func(i int, _ interface{}) bool {
		if i != idx {
			t.Errorf("i should be increased like idx in WhereIndexed with true predicate. expected(%v), got(%v)", idx, i)
		}
		idx++
		return true
	}).Results()
}

// this will pass
func TestWhereIndexedWithFalsePredicate(t *testing.T) {
	var idx int
	linq.From(l).WhereIndexed(func(i int, _ interface{}) bool {
		if i != idx {
			t.Errorf("i should be increased like idx in WhereIndexed with false predicate. expected(%v), got(%v)", idx, i)
		}
		idx++
		return false
	}).Results()
}

// suppose there's no different between ForEachIndexed and WhereIndexed as for index behavior
// this will pass
func TestForEachIndexed(t *testing.T) {
	var idx int
	linq.From(l).ForEachIndexed(func(i int, _ interface{}) {
		if i != idx {
			t.Errorf("i should be increased like idx in ForEachIndexed. expected(%v), got(%v)", idx, i)
		}
		idx++
	})
}
```

**Comment by ahmetb** [comment]
> hi, here's the test case:

sorry I meant to say, can you send a PR with this test case?

**Comment by ahmetb** [comment]
https://github.com/ahmetb/go-linq/blob/b1b02a14bd27fab06f03ca1e4eed893f5011c152/where_test.go#L32

for example we have this test case, you can add it next to that.
also do you have any idea why this test case passes? sorry I'm rusty a bit on this codebase.

**Comment by quexer** [comment]
hi  @ahmetb , here's the PR:

https://github.com/ahmetb/go-linq/pull/87

what I'm confused is all about the picture below

![image](https://user-images.githubusercontent.com/92157/67621568-11677180-f843-11e9-8520-07f6efaecdba.png)

**Comment by ahmetb** [comment]
Yeah I'm surprised the `[9]int{1, 1, 1, 2, 1, 2, 3, 4, 2}` test is passing but yours in #87 isn't. 

The part you highlighted seems accurate. First param passed to `predicate` is the index of element (starting from 0) in the collection, second param is its value.

**Comment by quexer** [comment]
If the highlighted part is accurate, then I'm sure there's bug in `WhereIndexed`
