### ISSUE TITLE
Article comparing performance of go-linq vs others

### ISSUE THREAD

**Issue by ahmetb** [ahmetb/go-linq#91]
For maintainers:

https://medium.com/wesovilabs/koazee-vs-go-funk-vs-go-linq-caf8ef18584e

**Comment by kalaninja** [comment]
The benchmark seems inaccurate. I'll write it to the guy.

**Comment by kalaninja** [comment]
@ahmetb @cleitonmarx guys, I've published a reply to the post.
https://medium.com/@kalansoft/hi-iv%C3%A1n-corrales-solera-8459e3eed4c6

**Comment by ahmetb** [comment]
Thanks that’s cool I didn’t understand the specifics but thanks for taking the time.

**Comment by kalaninja** [comment]
@ahmetb the idea is that koazee utilizes a push model. So it manipulates data the same order you write functions. E.g. if you take an array of 100 elements, filter it and take just 1 element - it will filter all the data into a new array first and take the first element afterwards. While go-linq uses a pull model and goes the other direction, so in the example above it will look through the initial array until the first element that satisfies the condition. No extra work.

If you finally decide to move go-linq to a team account I will make a second repo with benchmark comparison to the competitors. Also, I have plans to work on go-linq performance - introduce hints similar to rust iterators. Having a separate repo will help me to measure and show the performance difference.

**Comment by ahmetb** [comment]
Honestly since we're mostly in maintenance mode and there'll be 1 repo, creating a go-linq org might not be all that useful. If you would like to write an article, you can create a personal repo and publish benchmarks there as well?
