### ISSUE TITLE
gopkg.in/ahmetb/go-linq.v3: gopkg.in/ahmetb/go-linq.v3@v3.1.0: parsing go.mod:         module declares its path as: github.com/ahmetb/go-linq/v3 but was required as: gopkg.in/ahmetb/go-linq.v3

### ISSUE THREAD

**Issue by aparnag07** [ahmetb/go-linq#92]
I am trying to do create go.mod in my project. And this error arrives what should I do. I have imported 
gopkg.in/ahmetb/go-linq.v3 this package in my project files

**Comment by ahmetb** [comment]
🤔 try the github import path for now. I suspect our go.mod file is not correct. We might need to consolidate the import paths into one.

**Comment by aparnag07** [comment]
@ahmetb Thank you for reply. Will check it by using github import path

**Comment by aparnag07** [comment]
@ahmetb Even after using github path it gives same error

**Comment by belekarpavan** [comment]
I am also facing same issue while creating go.mod file.
I don't understand why this happening.
can you please help us.

**Comment by ahmetb** [comment]
Hi folks, as the readme clearly says, if you're using Go modules, you need to use `go get github.com/ahmetb/go-linq/v3`. The `gopkg.in` URL is provided for older Go versions where vgo isn't available.
